---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  maintenance-updates:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
    patterns: [ "*" ]
    multi-ecosystem-group: "maintenance-updates"
  - package-ecosystem: "maven"
    directory: "/"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
    patterns: [ "*" ]
    multi-ecosystem-group: "maintenance-updates"
  - package-ecosystem: "docker"
    directory: "/"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
    patterns: [ "*" ]
    multi-ecosystem-group: "maintenance-updates"
